### ISSUE TITLE
Should not use fix for Closure Compiler ES5 output

### ISSUE THREAD

**Issue by ikabirov** [ungap/template-literal#4]
Closure Compiler output is correct (template reference will be always the same)

https://closure-compiler-debugger.appspot.com/#input0%3Dfunction%2520run()%2520%257B%250A%2520%2520return%2520String.raw%2560%253Cli%253E%253C%252Fli%253E%2560%253B%250A%257D%250Arun()%253B%26input1%26conformanceConfig%26externs%3Dvar%2520console%2520%253D%2520%257B%257D%250Aconsole.log%2520%253D%2520(a)%2520%253D%253E%2520%257B%257D%26refasterjs-template%26includeDefaultExterns%3Dtrue%26CHECK_TYPES%3Dtrue%26CHECK_SYMBOLS%3Dtrue%26MISSING_PROPERTIES%3Dtrue%26TRANSPILE%3Dtrue%26PRESERVE_TYPE_ANNOTATIONS%3Dtrue%26PRETTY_PRINT%3Dtrue

**Comment by WebReflection** [comment]
Impossible to know upfront, this is an easy won't fix.

**Comment by WebReflection** [comment]
FYI I think the solution with bundlers is to resolve `@ungap/template-literal` as `@ungap/no-template-literal` so that you'll get a no-op version of the `@ungap/template-literal`.

I've just published it https://github.com/ungap/no-template-literal/blob/master/esm/index.js and I might follow the same convention for other cases (when needed, and when I'll have time)

/cc @coreyfarrell

**Comment by coreyfarrell** [comment]
For the `remove-ungap` babel plugin I'm going to stay with the current approach of removing the import statements, rather than replacing with an alternative import.  The reason is that my development web server supports browsing 'live source' processed by babel but not bundled.  So in that scenario `remove-ungap` is decreasing the total number of requests which has an effect on load time for the development server.

The only current module that I would consider using a replacement import would be if you created an `@ungap/create-content-modern`, then I could replace the `@ungap/create-content` instead of directly editing the `var HAS_CONTENT` statement inside that module.  For that it would be important that `@ungap/create-content` force `@ungap/create-content-modern` to install, otherwise the replacement import could fail.  I don't want `remove-ungap` to require that users explicitly install any replacement packages.
